### ISSUE TITLE
Port to meson

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/libalternatives#14]
With recent changes being submitted, libalternatives seems to find its way into the distro bootstrap cycle (Ring0)

cmake is not exactly the best option in this case - we already have two full build systems in Ring0 (autoFOO and meson) and it would thus be beneficial, from a distro pov, to use one of the two. Meson is one of the probably most maintained build systems out there at this moment (used by systemd, X.org, most of the GNOME stack)

**Comment by AdamMajer** [comment]
Thanks, I've just added this yesterday in https://github.com/openSUSE/libalternatives/commit/3fb80dcc132567be1274e1c9409bf30fed4f05f8 . Now it needs to be added and used by the package. Do we have some build flag to differentiate build during bootstrap vs. not? Like `%if 0%{?bootstrap}` ?

**Comment by DimStar77** [comment]
No, we have no flag - and it would be about the worst thing to do if the ring builds / stagins builds and product builds would not be the same. This would invalidate all testing

if cmake is only used for the test suite though: can we run it in two phases as multibuild?

i.e. primary phase builds the stuff and makes it usable for other packages, 2nd flavor runs the test suite over what was built/installed in phase 1?

**Comment by AdamMajer** [comment]
Well, reproducible builds? The aim is to have exactly the same binary in both types of builds - cmake vs. makefile.

The testing build is actually different than the production build anyway since different paths are compiled in.

**Comment by AdamMajer** [comment]
Which actually is a good idea to test in %check target -- whether the build is reproducible.
