### ISSUE TITLE
Add manual page

### ISSUE THREAD

**Issue by AdamMajer** [openSUSE/libalternatives#4]
alts.1

**Comment by bnavigator** [comment]
Typos in the current alts page/help screen:

"alts  is  a  **defaul**  program manager"
"-s -- system **overrude**, default for root users"

**Comment by AdamMajer** [comment]
Fixed by https://github.com/openSUSE/libalternatives/commit/ee5a0622900f6b395eb6a89a714e4f7f3fbe19ff and others. Though it needs expanding
